Header header

time stamp

#ObjectDetects objDetects

bool      motion_detected
box       roi

multiBox  peopleDetects

bool[]      poi
bool[]      ooi

multiBox  ooi_position
multiBox  poi_postion

string[] objRecog
string[] peopleRecog



#uint8 msgtype
#uint8 len
#uint8[] data
#uint32 times_ms
#uint16 time_us
#uint32 id


#string frame_id
#string EXAMPLE=''
#duration 
#bool       #unsigned 8-bit int




