# goal

geometry_msgs/Pose goal_pose

---
#result
uint8 result

uint8 PENDING   = 0
uint8 ACTIVE    = 1
uint8 PREEMPTED = 2
uint8 SUCCEEDED = 3
uint8 ABORTED   = 4
uint8 REJECTED  = 5
uint8 PREEMPTING= 6
uint8 RECALLING = 7
uint8 RECALLED  = 8
uint8 LOST      = 9

---
#feedback

geometry_msgs/Pose current_pose
